version: '3.8'
services:
  frontend:
    image: nginx
    container_name: frontend
    hostname: frontend
    environment:
      - TZ="America/Denver"
    volumes:
      - ./frontend/config/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/config/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
  backend01:
    image: nginx
    container_name: backend01
    hostname: backend01
    environment:
      - TZ="America/Denver"
    volumes:
      - ./backend/config/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/www:/usr/share/nginx/html
      - ./backend/config/conf.d:/etc/nginx/conf.d
  backend02:
    image: nginx
    container_name: backend02
    hostname: backend02
    environment:
      - TZ="America/Denver"
    volumes:
      - ./backend/config/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/www:/usr/share/nginx/html
      - ./backend/config/conf.d:/etc/nginx/conf.d
  backend03:
    image: nginx
    container_name: backend03
    hostname: backend03
    environment:
      - TZ="America/Denver"
    volumes:
      - ./backend/config/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/www:/usr/share/nginx/html
      - ./backend/config/conf.d:/etc/nginx/conf.d
