name: porter-bundle-publish

on:
  push:
    branches:
      - "**"
    tags:
      - v*
    paths-ignore:
      - "**/README.md"

# Set up environment variables needed for the bundle.
# If these are sensitive, they should be set as secrets in the repository.
# To do this, go to settings -> secrets -> new secret.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: bdegeeter/joyofnginx/nginx-oss

# A workflow can be made of many jobs, but this example puts all the steps under one job.
jobs:
  # Publish is the name of this job.
  publish:
    if: github.event_name == 'push'
    # Specify the type of machine you want the job to run on. We chose ubuntu-latest.
    runs-on: ubuntu-latest
    steps:
      # Check out code
      - uses: actions/checkout@v3
      # Use Porter GH action to set up Porter.
      # You can specify the version of Porter that you want installed by adding the lines for with and porter_version as explained above.
      - name: Setup Porter
        uses: getporter/gh-action@v0.1.3
      - name: Install Porter mixins
        run: |
          porter mixins install az --version v1.0.0-rc.2
          porter mixins install terraform --version v1.0.0-rc.2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
      - name: get porter bundle version
        id: bundleVersion
        uses: mikefarah/yq@v4.9.6
        with:
          cmd: yq e '.version' porter/nginx-oss/porter.yaml
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_TOKEN }}
      # Run publish.
      # If any of the porter commands above fail, the workflow will stop, so your bundle will only be published if it works properly.
      - name: Porter Publish Tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          make publish-porter-nginx-oss BUNDLE_VERSION=${{ steps.meta.outputs.version }}
          make update-porter-yaml-version update-porter-docs BUNDLE_VERSION=${{ steps.meta.outputs.version }}
      - name: Porter Publish Branch
        if: ${{ startsWith(github.ref, 'refs/heads/') }}
        run: |
          make publish-porter-nginx-oss BUNDLE_VERSION=${{ steps.bundleVersion.outputs.result }}-${{ steps.meta.outputs.version }}
      - name: Update resources
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            porter/nginx-oss/README.md
            porter/nginx-oss/porter.yaml
          commit-msg: "[no ci] update cnab bundle version"
          github-token: ${{ secrets.GITHUB_TOKEN }}
